import GoogleSuggestions from './components/GoogleSuggestions'

import './App.css'



const suggestionsList = [
  {
    id: 1,
    suggestion: 'United States',
    capital: 'Washington, D.C.',
    population: 331002651,
    official_language: 'English',
    currency: 'United States Dollar',
  },
  {
    id: 2,
    suggestion: 'Canada',
    capital: 'Ottawa',
    population: 37742154,
    official_language: ['English', 'French'],
    currency: 'Canadian Dollar',
  },
  {
    id: 3,
    suggestion: 'Brazil',
    capital: 'Brasília',
    population: 212559417,
    official_language: 'Portuguese',
    currency: 'Brazilian Real',
  },
  {
    id: 4,
    suggestion: 'United Kingdom',
    capital: 'London',
    population: 67886011,
    official_language: 'English',
    currency: 'Pound Sterling',
  },
  {
    id: 5,
    suggestion: 'Australia',
    capital: 'Canberra',
    population: 25409800,
    official_language: 'English',
    currency: 'Australian Dollar',
  },
  {
    id: 6,
    suggestion: 'Germany',
    capital: 'Berlin',
    population: 83783942,
    official_language: 'German',
    currency: 'Euro',
  },
  {
    id: 7,
    suggestion: 'France',
    capital: 'Paris',
    population: 65273511,
    official_language: 'French',
    currency: 'Euro',
  },
  {
    id: 8,
    suggestion: 'Italy',
    capital: 'Rome',
    population: 60244639,
    official_language: 'Italian',
    currency: 'Euro',
  },
  {
    id: 9,
    suggestion: 'Spain',
    capital: 'Madrid',
    population: 46754778,
    official_language: 'Spanish',
    currency: 'Euro',
  },
  {
    id: 10,
    suggestion: 'Japan',
    capital: 'Tokyo',
    population: 126476461,
    official_language: 'Japanese',
    currency: 'Japanese Yen',
  },
  {
    id: 11,
    suggestion: 'China',
    capital: 'Beijing',
    population: 1393409038,
    official_language: 'Mandarin',
    currency: 'Renminbi',
  },
  {
    id: 12,
    suggestion: 'India',
    capital: 'New Delhi',
    population: 1380004385,
    official_language: ['Hindi', 'English'],
    currency: 'Indian Rupee',
  },
  {
    id: 13,
    suggestion: 'South Africa',
    capital: 'Pretoria',
    population: 59308690,
    official_language: ['Zulu', 'Xhosa', 'Afrikaans', 'English'],
    currency: 'South African Rand',
  },
  {
    id: 14,
    suggestion: 'Russia',
    capital: 'Moscow',
    population: 145912025,
    official_language: 'Russian',
    currency: 'Russian Ruble',
  },
  {
    id: 15,
    suggestion: 'Mexico',
    capital: 'Mexico City',
    population: 128932753,
    official_language: 'Spanish',
    currency: 'Mexican Peso',
  },
  {
    id: 16,
    suggestion: 'Argentina',
    capital: 'Buenos Aires',
    population: 45195777,
    official_language: 'Spanish',
    currency: 'Argentine Peso',
  },
  {
    id: 17,
    suggestion: 'Chile',
    capital: 'Santiago',
    population: 19116201,
    official_language: 'Spanish',
    currency: 'Chilean Peso',
  },
  {
    id: 18,
    suggestion: 'Colombia',
    capital: 'Bogotá',
    population: 50882891,
    official_language: 'Spanish',
    currency: 'Colombian Peso',
  },
  {
    id: 19,
    suggestion: 'Peru',
    capital: 'Lima',
    population: 32971854,
    official_language: ['Spanish', 'Quechua', 'Aymara'],
    currency: 'Peruvian Sol',
  },
  {
    id: 20,
    suggestion: 'Egypt',
    capital: 'Cairo',
    population: 91250000,
    official_language: 'Arabic',
    currency: 'Egyptian Pound',
  },
  {
    id: 21,
    suggestion: 'Turkey',
    capital: 'Ankara',
    population: 84339067,
    official_language: 'Turkish',
    currency: 'Turkish Lira',
  },
  {
    id: 22,
    suggestion: 'Nigeria',
    capital: 'Abuja',
    population: 206139589,
    official_language: 'English',
    currency: 'Nigerian Naira',
  },
  {
    id: 23,
    suggestion: 'Kenya',
    capital: 'Nairobi',
    population: 53771296,
    official_language: ['Swahili', 'English'],
    currency: 'Kenyan Shilling',
  },
  {
    id: 24,
    suggestion: 'Ghana',
    capital: 'Accra',
    population: 31072940,
    official_language: 'English',
    currency: 'Ghanaian Cedi',
  },
  {
    id: 25,
    suggestion: 'South Korea',
    capital: 'Seoul',
    population: 51269185,
    official_language: 'Korean',
    currency: 'South Korean Won',
  },
  {
    id: 26,
    suggestion: 'Thailand',
    capital: 'Bangkok',
    population: 69799978,
    official_language: 'Thai',
    currency: 'Thai Baht',
  },
  {
    id: 27,
    suggestion: 'Malaysia',
    capital: 'Kuala Lumpur',
    population: 32365999,
    official_language: 'Malay',
    currency: 'Malaysian Ringgit',
  },
  {
    id: 28,
    suggestion: 'Vietnam',
    capital: 'Hanoi',
    population: 97338579,
    official_language: 'Vietnamese',
    currency: 'Vietnamese Dong',
  },
  {
    id: 29,
    suggestion: 'Singapore',
    capital: 'Singapore',
    population: 5850342,
    official_language: ['English', 'Mandarin', 'Malay', 'Tamil'],
    currency: 'Singapore Dollar',
  },
  {
    id: 30,
    suggestion: 'New Zealand',
    capital: 'Wellington',
    population: 4822233,
    official_language: ['English', 'Māori'],
    currency: 'New Zealand Dollar',
  },
  {
    id: 31,
    suggestion: 'Sweden',
    capital: 'Stockholm',
    population: 10099270,
    official_language: 'Swedish',
    currency: 'Swedish Krona',
  },
  {
    id: 32,
    suggestion: 'Norway',
    capital: 'Oslo',
    population: 5421241,
    official_language: 'Norwegian',
    currency: 'Norwegian Krone',
  },
  {
    id: 33,
    suggestion: 'Finland',
    capital: 'Helsinki',
    population: 5540720,
    official_language: ['Finnish', 'Swedish'],
    currency: 'Euro',
  },
  {
    id: 34,
    suggestion: 'Denmark',
    capital: 'Copenhagen',
    population: 5792202,
    official_language: 'Danish',
    currency: 'Danish Krone',
  },
  {
    id: 35,
    suggestion: 'Ireland',
    capital: 'Dublin',
    population: 4937786,
    official_language: ['Irish', 'English'],
    currency: 'Euro',
  },
  {
    id: 36,
    suggestion: 'Belgium',
    capital: 'Brussels',
    population: 11589623,
    official_language: ['Dutch', 'French', 'German'],
    currency: 'Euro',
  },
  {
    id: 37,
    suggestion: 'Netherlands',
    capital: 'Amsterdam',
    population: 17134872,
  },
]

const App = () => <GoogleSuggestions suggestionsList={suggestionsList} />

export default App
